### PR TITLE
Fix key lint check to avoid false positives

### LINKED ISSUE #550: Lint for keys in single-item lists cause false positives
For the following code:
```dart
var myList = [(Foo()..key = 1)()];

if (someCodition) {
  myList.add((Bar()..key = 2)())
}
```

We get a lint on `Foo` that the key is unnecessary, when it actually is necessary since other items are added to the list.

### PR DESCRIPTION
**Pull request by joebingham-wk**
## Motivation
  
Resolves #550. Single key lists with just children that are not part of a component usage should not have key warnings. 
## Changes
  
- Update list item check to also see if the list is part of a component usage.
## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

File: tools/analyzer_plugin/lib/src/diagnostic/single_child_key.dart [hunk 1]
```diff
@@ -21,7 +21,9 @@ class SingleChildWithKey extends ComponentUsageDiagnosticContributor {
     final parentMethodName = usage.node.thisOrAncestorOfType<MethodDeclaration>()?.name?.name;
 
     final parent = usage.node.parent;
-    if (parent is ListLiteral && (parent?.parent is! ReturnStatement)) {
+    // Being a list literal, the grandparent should be another component usage. Otherwise, the list may still
+    // easily be manipulated.
```
Comment (greglittlefield-wf) [inline tools/analyzer_plugin/lib/src/diagnostic/single_child_key.dart:25]: Could we reword this comment? I'm not quite sure what this is saying, especially this part:

> Otherwise, the list may still easily be manipulated.

Comment (greglittlefield-wf) [reply tools/analyzer_plugin/lib/src/diagnostic/single_child_key.dart:25]: Also, did you see this thread? https://workiva.slack.com/archives/CFM41D7C1/p1593102720005300?thread_ts=1593102203.002800&cid=CFM41D7C1

> luis.gomez  5 hours ago
> Iterable with 1 member missing key **does** throw a React runtime warning
>
>corwin.sheahan  5 hours ago
> IMO if the react runtime throws a warning for that, we probably should too :shrug:__

Sounds like we should still warn when the list only has a single child, which means we need to update this logic

Comment (joebingham-wk) [reply tools/analyzer_plugin/lib/src/diagnostic/single_child_key.dart:25]: Yep! I can update the comment. Doesn't this achieve that goal though? I thought that's what this lint originally did and we needed to make it more focused

Comment (joebingham-wk) [reply tools/analyzer_plugin/lib/src/diagnostic/single_child_key.dart:25]: Oh, wait, nevermind haha

Comment (joebingham-wk) [reply tools/analyzer_plugin/lib/src/diagnostic/single_child_key.dart]: Updated @greglittlefield-wf! I renamed a bunch of stuff because I think this lint was now doing an entirely different thing than it originally was haha
